Update to 1.5.3

diff --git a/.github/workflows/build-and-release.yml b/.github/workflows/build-and-release.yml
--- a/.github/workflows/build-and-release.yml
+++ b/.github/workflows/build-and-release.yml
@@ -13,7 +13,7 @@ jobs:
     name: Build (${{ matrix.os }}, ${{ matrix.python-version }}${{ matrix.clang && format(', {0}', matrix.clang-version) || '' }})
     strategy:
       matrix:
-        os: [ubuntu-latest] #, windows-latest, macos-15, macos-15-intel]
+        os: [ubuntu-latest, windows-latest, macos-15, macos-15-intel]
         include:
           - os: ubuntu-latest
             platform: linux
@@ -21,24 +21,24 @@ jobs:
             nuitka: true
             clang: true
             clang-version: 22.1.3
-          # - os: windows-latest
-          #   platform: windows
-          #   python-version: 3.14
-          #   nuitka: true
-          #   clang: False   # https://github.com/Nuitka/Nuitka/issues/3621
-          #   clang-version: 21.1.8
-          # - os: macos-15
-          #   platform: macos
-          #   python-version: 3.14
-          #   nuitka: false
-          #   clang: true
-          #   clang-version: 21.1.8
-          # - os: macos-15-intel
-          #   platform: macos
-          #   python-version: 3.14
-          #   nuitka: false
-          #   clang: true
-          #   clang-version: 21.1.8
+          - os: windows-latest
+            platform: windows
+            python-version: 3.14
+            nuitka: true
+            clang: False   # https://github.com/Nuitka/Nuitka/issues/3621
+            clang-version: 21.1.8
+          - os: macos-15
+            platform: macos
+            python-version: 3.14
+            nuitka: false
+            clang: true
+            clang-version: 21.1.8
+          - os: macos-15-intel
+            platform: macos
+            python-version: 3.14
+            nuitka: false
+            clang: true
+            clang-version: 21.1.8
     runs-on: ${{ matrix.os }}
     permissions:
       contents: read
@@ -89,6 +89,7 @@ jobs:
       - name: Install macOS system dependencies
         if: matrix.platform == 'macos'
         run: |
+          brew untap aws/tap 2>/dev/null || true
           brew install ccache
           echo "SDKROOT=$(xcrun --sdk macosx --show-sdk-path)" >> $GITHUB_ENV
 
@@ -139,9 +140,14 @@ jobs:
         shell: bash
         run: |
           chmod +x ./tools/build_python.sh
+          CURSES_VERSION=$(sed -n '/^\[build\]/,/^\[/p' pyproject.toml | grep '^curses_tag' | cut -d '"' -f 2)
+          if [ -z "$CURSES_VERSION" ]; then
+            echo "Error: Could not extract curses_tag from pyproject.toml"
+            exit 1
+          fi
           args=("${{ matrix.python-version }}")
           [[ "${{ matrix.clang }}" == "true" ]] && args+=("clang")
-          ./tools/build_python.sh "${args[@]}" curses v6_6_20260627
+          ./tools/build_python.sh "${args[@]}" curses "$CURSES_VERSION"
 
       - name: Install uv
         uses: astral-sh/setup-uv@v7
@@ -158,16 +164,16 @@ jobs:
             [[ "${{ matrix.nuitka }}" == "true" ]] && args+=("--nuitka")
             [[ "${{ matrix.clang }}" != "true" ]] && args+=("--noclang")
             [[ "${{ runner.os }}" == "Linux" ]] && args+=("--custom-python")
-            uv run build.py "${args[@]}"
+            uv run build.py --level=FULL "${args[@]}"
 
-      # - name: Run build lite script
-      #   shell: bash
-      #   run: |
-      #       args=()
-      #       [[ "${{ matrix.nuitka }}" == "true" ]] && args+=("--nuitka")
-      #       [[ "${{ matrix.clang }}" != "true" ]] && args+=("--noclang")
-      #       [[ "${{ runner.os }}" == "Linux" ]] && args+=("--custom-python")
-      #       uv run build.py --lite "${args[@]}"
+      - name: Run build lite script
+        shell: bash
+        run: |
+            args=()
+            [[ "${{ matrix.nuitka }}" == "true" ]] && args+=("--nuitka")
+            [[ "${{ matrix.clang }}" != "true" ]] && args+=("--noclang")
+            [[ "${{ runner.os }}" == "Linux" ]] && args+=("--custom-python")
+            uv run build.py --level=LITE "${args[@]}"
 
       - name: Make binaries executable
         if: matrix.platform == 'macos' || matrix.platform == 'linux'
@@ -184,7 +190,7 @@ jobs:
           cp ../docs/{commands.md,configuration.md,extensions.md,keybindings.md} docs/
           if [[ "${{ matrix.platform }}" == "linux" ]]; then
             tar -czf "endcord-$version-${{ matrix.platform }}.tar.gz" endcord $extra
-            # tar -czf "endcord-lite-$version-${{ matrix.platform }}.tar.gz" endcord-lite $extra
+            tar -czf "endcord-lite-$version-${{ matrix.platform }}.tar.gz" endcord-lite $extra
           elif [[ "${{ matrix.platform }}" == "windows" ]]; then
             7z a "endcord-$version-${{ matrix.platform }}.zip" endcord.exe $extra
             7z a "endcord-lite-$version-${{ matrix.platform }}.zip" endcord-lite.exe $extra
@@ -246,7 +252,6 @@ jobs:
         with:
           name: '${{ steps.extract_version.outputs.version }} [DRAFTED BY CI]'
           tag_name: '${{ steps.extract_version.outputs.version }}'
-          target_commitish: ${{ github.sha }}
           draft: true
           prerelease: ${{ contains(steps.extract_version.outputs.version, 'dev') }}
           files: dist/*
